# Generated by Django 5.2.16 on 2026-07-23 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_rename_notes_loanproduct_internal_notes_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="loan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="loans.loanproduct",
            ),
        ),
    ]
