# Generated by Django 5.2.16 on 2026-08-10 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_paymentrecord_is_reversed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="payment_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
