# Generated by Django 5.2.16 on 2026-08-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_paymentrecord_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="quickbooks_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
