# Generated by Django 5.2.16 on 2026-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_paymentrecord_quickbooks_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="deposit_applied",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Deposit portion applied at confirmation time",
                max_digits=12,
            ),
        ),
    ]
