# Generated by Django 5.1.3 on 2026-06-15 15:35

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinanceApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "your_name",
                    models.CharField(max_length=255, verbose_name="Your name"),
                ),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                (
                    "nationality",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nationality"
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ID Number"
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("National ID card", "National ID card"),
                            ("Valid Passport", "Valid Passport"),
                            ("Valid Drivers license", "Valid Drivers license"),
                        ],
                        max_length=50,
                        verbose_name="ID Type",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                        ],
                        max_length=20,
                        verbose_name="Marital Status",
                    ),
                ),
                (
                    "num_of_dependents",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Number of Dependents",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "time_at_address",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Length of Time at Address (Years)",
                    ),
                ),
                ("tel", models.CharField(max_length=20, verbose_name="Cell Phone")),
                (
                    "your_email",
                    models.EmailField(max_length=254, verbose_name="Your email"),
                ),
                (
                    "existing_essco",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=3,
                        verbose_name="Existing ESSCO Customer?",
                    ),
                ),
                (
                    "employer_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Employer Name"
                    ),
                ),
                (
                    "employer_address",
                    models.TextField(blank=True, verbose_name="Employer Address"),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Permanent", "Permanent"),
                            ("Contract", "Contract"),
                            ("Probationary", "Probationary"),
                            ("Self-Employed", "Self-Employed"),
                        ],
                        max_length=20,
                        verbose_name="Employer Type",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Job Title"
                    ),
                ),
                (
                    "two_years_employment_select",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=3,
                        null=True,
                        verbose_name="Is your current employment less than 2 years?",
                    ),
                ),
                (
                    "gross_monthly_income_more",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Gross Monthly Income",
                    ),
                ),
                (
                    "length_employment_more",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(24)],
                        verbose_name="Length of Employment (Months)",
                    ),
                ),
                (
                    "length_employment_less",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(23),
                        ],
                        verbose_name="Length of Employment (Months)",
                    ),
                ),
                (
                    "previous_employer",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Previous Employer"
                    ),
                ),
                (
                    "total_purchase_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total Purchase Value",
                    ),
                ),
                (
                    "loan_mortgages_payments",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Loan mortgages payments",
                    ),
                ),
                (
                    "credit_card_payments",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Credit Card Payments",
                    ),
                ),
                (
                    "other_debt_payments",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Other Debt Payments",
                    ),
                ),
                (
                    "rent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Rent",
                    ),
                ),
                (
                    "utilities",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Utilities",
                    ),
                ),
                (
                    "food",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Food",
                    ),
                ),
                (
                    "transportation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Transportation",
                    ),
                ),
                (
                    "insurance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Insurance",
                    ),
                ),
                (
                    "other_living_expenses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Other Living Expenses",
                    ),
                ),
                (
                    "reference1_full_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Reference 1 - Full Name",
                    ),
                ),
                (
                    "reference1_relationship",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Reference 1 - Relationship",
                    ),
                ),
                (
                    "reference1_employer",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Reference 1 - Employer",
                    ),
                ),
                (
                    "reference1_job_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Reference 1 - Job Title",
                    ),
                ),
                (
                    "reference1_contact_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Reference 1 - Contact Number",
                    ),
                ),
                (
                    "reference1_length_of_time_known",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Reference 1 - Length of Time Known",
                    ),
                ),
                (
                    "reference2_full_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Reference 2 - Full Name",
                    ),
                ),
                (
                    "reference2_relationship",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Reference 2 - Relationship",
                    ),
                ),
                (
                    "reference2_employer",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Reference 2 - Employer",
                    ),
                ),
                (
                    "reference2_job_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Reference 2 - Job Title",
                    ),
                ),
                (
                    "reference2_contact_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Reference 2 - Contact Number",
                    ),
                ),
                (
                    "reference2_length_of_time_known",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Reference 2 - Length of Time Known",
                    ),
                ),
                (
                    "preferred_communication_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Email", "Email"),
                            ("Text Message (SMS)", "Text Message (SMS)"),
                            ("WhatsApp", "WhatsApp"),
                        ],
                        max_length=50,
                        verbose_name="Preferred Communication Method",
                    ),
                ),
                (
                    "identification",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/identification/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "pdf",
                                    "mp4",
                                    "avi",
                                    "mov",
                                    "mp3",
                                    "wav",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "job_letter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/job_letters/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "payslips",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/payslips/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "business_registration",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/business_registration/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "financial_statements",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/financial_statements/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "self_employed_bank_statements",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/bank_statements_self/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "utility_bill",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/utility_bills/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "bank_statements",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/bank_statements/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "selfie",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/selfies/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "total_monthly_living_expenses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_monthly_debt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "monthly_obligations",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "disposable_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "debt_to_income_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=5, null=True
                    ),
                ),
                (
                    "living_expenses_to_income_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=5, null=True
                    ),
                ),
                (
                    "total_debt_service_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=5, null=True
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "financed_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        blank=True, default="Pending Review", max_length=50
                    ),
                ),
                (
                    "total_credit_allowed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total_repayment_amount_six",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total_repayment_amount_twelve",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total_repayment_amount_eighteen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total_repayment_amount_twenty_four",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total_repayment_amount_thirty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "total_repayment_amount_thirty_six",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "six_month_installment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "twelve_month_installment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "eighteen_month_installment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "twenty_four_month_installment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "thirty_month_installment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "thirty_six_month_installment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "final_step",
                    models.CharField(blank=True, default="Select", max_length=50),
                ),
                (
                    "monthly_plan",
                    models.CharField(blank=True, default="Select", max_length=50),
                ),
                (
                    "submission_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Finance Application",
                "verbose_name_plural": "Finance Applications",
                "ordering": ["-submission_date"],
            },
        ),
    ]
