# Generated by Django 5.1.3 on 2026-06-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FinanceApplication",
        ),
    ]
