# Generated by Django 5.1.3 on 2026-06-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0002_delete_financeapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fname", models.CharField(max_length=100)),
                ("Lname", models.CharField(max_length=100)),
                ("Gender", models.CharField(blank=True, max_length=50, null=True)),
                ("food", models.DecimalField(decimal_places=2, max_digits=10)),
                ("utilities", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "living_expenses",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
