# Generated by Django 5.1.3 on 2026-06-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationmodel",
            name="living_expenses",
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="CCPayments",
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Cell_Phone",
            field=models.IntegerField(default=3234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="DOB",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Employer_Address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Employer_Name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Employer_Type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Permanent", "Permanent"),
                    ("Contract", "Contract"),
                    ("Probationary", "Probationary"),
                    ("Self-Employed", "Self-Employed"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Existing_Customer",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="Yes", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Gross_Monthly_Income",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="ID_Type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("National ID card", "National ID card"),
                    ("Valid Passport", "Valid Passport"),
                    ("Valid Drivers license", "Valid Drivers license"),
                ],
                default="National ID card",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="ID_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Insurance",
            field=models.DecimalField(decimal_places=2, default=32, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Job_Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Len_Employ",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Length_at_Address",
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Loan_mortgages_payments",
            field=models.DecimalField(decimal_places=2, default=324, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Marital_Status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                    ("Widowed", "Widowed"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Monthly_Obligations",
            field=models.DecimalField(decimal_places=2, default=324, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Nationality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Num_Dependents",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Other_Debt_Payments",
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Other_Living_Expenses",
            field=models.DecimalField(decimal_places=2, default=234, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Previous_Employer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Purchase_Value",
            field=models.DecimalField(decimal_places=2, default=4333, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Reference1_Contact_Number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Reference1_Employer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Reference1_FullName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Reference1_Job_Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Reference1_Len_Time_Known",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Reference1_Relationship",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Reference2_Contact_Number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Reference2_Employer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Reference2_FullName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Reference2_Job_Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Reference2_Len_Time_Known",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Reference2_Relationship",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Rent",
            field=models.DecimalField(decimal_places=2, default=32, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Total_Monthly_debt",
            field=models.DecimalField(decimal_places=2, default=43, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Total_Monthly_living_expenses",
            field=models.DecimalField(decimal_places=2, default=43, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Transportation",
            field=models.DecimalField(decimal_places=2, default=34, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="less_than_two_years",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default=43, max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Fname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Lname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
