# Generated by Django 5.1.3 on 2026-06-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_remove_applicationmodel_living_expenses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="Cell_Phone",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Len_Employ",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Length_at_Address",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Num_Dependents",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference1_Len_Time_Known",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference2_Len_Time_Known",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
