# Generated by Django 5.1.3 on 2026-06-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_alter_applicationmodel_cell_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="Debt_To_Income_Ratio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Disposable_Income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Living_Expense_Ratio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Total_Debt_Service_Ratio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
