# Generated by Django 5.1.3 on 2026-06-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_applicationmodel_debt_to_income_ratio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="Approval_Status",
            field=models.CharField(default="Rejected", max_length=100),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Deposit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Financed_Amt",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Total_Credit_Allowed",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
