# Generated by Django 5.1.3 on 2026-06-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_applicationmodel_approval_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="Residential_Status",
            field=models.CharField(
                choices=[
                    ("Owner", "Owner"),
                    ("Tenant", "Tenant"),
                    ("Living with Parents", "Living with Parents"),
                    ("Shared Rental", "Shared Rental"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Len_Employ",
            field=models.CharField(
                choices=[
                    ("2 + Years", "2 + Years"),
                    ("6 months to 2 years", "6 months to 2 years"),
                    ("Less than 6 months", "Less than 6 months"),
                ],
                default="2 + Years",
                max_length=50,
            ),
        ),
    ]
