# Generated by Django 5.1.3 on 2026-06-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_applicationmodel_residential_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="Reference1_Address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Reference2_Address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
