# Generated by Django 5.1.3 on 2026-06-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_applicationmodel_reference1_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="Eighteen",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Six",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Thirty",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Thirty_Six",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Twelve",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Twenty_Four",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
