# Generated by Django 6.0.6 on 2026-06-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0010_applicationmodel_eighteen_applicationmodel_six_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="CCPayments",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Cell_Phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="ID_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Insurance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Loan_mortgages_payments",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Other_Debt_Payments",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Other_Living_Expenses",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Purchase_Value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Rent",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Transportation",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="food",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="utilities",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
