# Generated by Django 6.0.6 on 2026-06-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_alter_applicationmodel_ccpayments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
