# Generated by Django 6.0.6 on 2026-06-22 15:53

import applications.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_applicationmodel_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="Bank_Statement",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/bank_statements/"
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Business_Registration",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/business_registration/"
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Financial_Statement",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/financial_statements/"
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Identification",
            field=models.FileField(
                blank=True, null=True, upload_to=applications.functions.id_upload_path
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Job_Letter",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applications.functions.Payslip_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Payslip",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applications.functions.Payslip_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Selfie",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/proof_of_address/"
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Statement",
            field=models.FileField(
                blank=True, null=True, upload_to=applications.functions.POA_upload_path
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Utility_Bill",
            field=models.FileField(
                blank=True, null=True, upload_to="applications/proof_of_address/"
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="ID_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="no_spaces",
                        message="Spaces are not allowed.",
                        regex="^[^\\s]+$",
                    )
                ],
            ),
        ),
    ]
