# Generated by Django 6.0.6 on 2026-06-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0014_applicationmodel_bank_statement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="Parish",
            field=models.CharField(
                choices=[
                    ("Christ Church", "Christ Church"),
                    ("Saint Philip", "Saint Philip"),
                    ("Saint Michael", "Saint Michael"),
                    ("Saint Thomas", "Saint Thomas"),
                    ("Other", "Other"),
                    ("Saint Peter", "Saint Peter"),
                    ("Saint Lucy", "Saint Lucy"),
                    ("Saint Joseph", "Saint Joseph"),
                    ("Saint John", "Saint John"),
                    ("Saint James", "Saint James"),
                    ("Saint George", "Saint George"),
                    ("Saint Andrew", "Saint Andrew"),
                ],
                default="Other",
                max_length=100,
            ),
        ),
    ]
