# Generated by Django 6.0.6 on 2026-06-22 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0016_alter_applicationmodel_parish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="ID_number",
            field=models.CharField(
                default=3453,
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="no_spaces",
                        message="Spaces are not allowed.",
                        regex="^[^\\s]+$",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
