# Generated by Django 6.0.6 on 2026-06-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0017_alter_applicationmodel_id_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="Final_Approval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Human Approved", "Human Approved"),
                    ("Human Rejected", "Human Rejected"),
                    ("other", "other"),
                ],
                default="other",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Identification_Check",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="other",
                max_length=50,
                null=True,
            ),
        ),
    ]
