# Generated by Django 6.0.6 on 2026-06-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0018_applicationmodel_final_approval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="Identification_Check",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=50,
                null=True,
            ),
        ),
    ]
