# Generated by Django 6.0.6 on 2026-06-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0019_alter_applicationmodel_identification_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="Disposable_Income_After",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Term",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Human Approved", "Human Approved"),
                    ("Human Rejected", "Human Rejected"),
                    ("other", "other"),
                ],
                default="other",
                max_length=50,
                null=True,
            ),
        ),
    ]
