# Generated by Django 6.0.6 on 2026-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0021_alter_applicationmodel_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="Term",
            field=models.CharField(
                blank=True,
                choices=[("Six", "Six"), ("Twelve", "Twelve"), ("other", "other")],
                default="Six",
                max_length=50,
                null=True,
            ),
        ),
    ]
