# Generated by Django 6.0.6 on 2026-06-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0022_alter_applicationmodel_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="Notes",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
