# Generated by Django 6.0.6 on 2026-06-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0023_applicationmodel_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="Notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
