# Generated by Django 6.0.6 on 2026-06-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0024_alter_applicationmodel_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="Term",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Six", "Six"),
                    ("Twelve", "Twelve"),
                    ("Eighteen", "Eighteen"),
                    ("Twenty Four", "Twenty Four"),
                    ("Thirty", "Thirty"),
                    ("Thirty Six", "Thirty Six"),
                    ("other", "other"),
                ],
                default="Six",
                max_length=50,
                null=True,
            ),
        ),
    ]
