# Generated by Django 6.0.6 on 2026-06-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0025_alter_applicationmodel_term"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicationmodel",
            old_name="less_than_two_years",
            new_name="less_than_six",
        ),
    ]
