# Generated by Django 6.0.6 on 2026-06-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0026_rename_less_than_two_years_applicationmodel_less_than_six",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="accept_terms",
            field=models.BooleanField(default=False),
        ),
    ]
