# Generated by Django 6.0.6 on 2026-06-29 16:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0028_alter_applicationmodel_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="Gross_Monthly_Income_AT",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="NIS",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="PAYE",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="RR",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Resilience & Regeneration (0.25% of gross)",
                max_digits=10,
            ),
        ),
    ]
