# Generated by Django 6.0.6 on 2026-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0030_alter_applicationmodel_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("supervisor", "Supervisor"),
                            ("agent", "Agent"),
                            ("admin", "Admin"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_approval_recipient", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "staff_members",
                "ordering": ["name"],
            },
        ),
    ]
