# Generated by Django 6.0.6 on 2026-07-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0031_staffmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
