# Generated by Django 6.0.6 on 2026-07-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0032_applicationmodel_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest_Rates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Rate_Name", models.CharField(blank=True, max_length=100, null=True)),
                ("Rate_Value", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
