# Generated by Django 6.0.6 on 2026-07-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0033_interest_rates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="DOB",
            field=models.DateField(default="2006-07-07"),
        ),
    ]
