# Generated by Django 6.0.6 on 2026-07-08 12:19

import applications.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0034_alter_applicationmodel_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="Address",
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Cell_Phone",
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Employer_Address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Employer_Name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Employer_Type",
            field=models.CharField(
                choices=[
                    ("Permanent", "Permanent"),
                    ("Contract", "Contract"),
                    ("Probationary", "Probationary"),
                    ("Self-Employed", "Self-Employed"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Fname",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Gross_Monthly_Income",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="ID_Type",
            field=models.CharField(
                choices=[
                    ("National ID card", "National ID card"),
                    ("Valid Passport", "Valid Passport"),
                    ("Valid Drivers license", "Valid Drivers license"),
                ],
                default="National ID card",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Identification",
            field=models.FileField(
                default=1, upload_to=applications.functions.id_upload_path
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Job_Title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Length_at_Address",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Lname",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Marital_Status",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                    ("Widowed", "Widowed"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Nationality",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Num_Dependents",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Previous_Employer",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Purchase_Value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference1_Address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference1_Contact_Number",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference1_Employer",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference1_FullName",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference1_Job_Title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference1_Len_Time_Known",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference1_Relationship",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference2_Address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference2_Contact_Number",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference2_Employer",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference2_FullName",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference2_Job_Title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference2_Len_Time_Known",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference2_Relationship",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Selfie",
            field=models.FileField(
                default=1, upload_to="applications/proof_of_address/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="email",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
