# Generated by Django 6.0.6 on 2026-07-13 17:02

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0035_alter_applicationmodel_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="item_name",
            field=models.CharField(
                default=applications.models.get_default_empty_string,
                help_text="Product name from WordPress",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="item_sku",
            field=models.CharField(
                default=applications.models.get_default_empty_string,
                help_text="Product SKU from WordPress",
                max_length=100,
            ),
        ),
    ]
