# Generated by Django 6.0.6 on 2026-07-13 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0036_applicationmodel_item_name_applicationmodel_item_sku"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'low'/Approved pending, 'Medium'/Human Review, 'High'/Rejected",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Interest rate as percentage (e.g., 5.00 = 5%)",
                        max_digits=5,
                    ),
                ),
                (
                    "min_loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=500.0,
                        help_text="Minimum loan amount for this rate",
                        max_digits=12,
                    ),
                ),
                (
                    "max_loan_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum loan amount (leave blank for no limit)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to disable this rate without deleting",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional information about this rate",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interest Rate",
                "verbose_name_plural": "Interest Rates",
                "ordering": ["rate"],
            },
        ),
    ]
