# Generated by Django 6.0.6 on 2026-07-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0038_alter_applicationmodel_num_dependents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="Length_at_Address",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference1_Len_Time_Known",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference2_Len_Time_Known",
            field=models.IntegerField(
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ]
            ),
        ),
    ]
