# Generated by Django 6.0.6 on 2026-07-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0039_alter_applicationmodel_length_at_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="Residential_Status",
            field=models.CharField(
                choices=[
                    ("Owner", "Owner"),
                    ("Tenant", "Tenant"),
                    ("Living with Parents", "Living with Parents"),
                    ("Shared Rental", "Shared Rental"),
                ],
                default="Owner",
                max_length=50,
            ),
        ),
    ]
