# Generated by Django 6.0.6 on 2026-07-17 20:35

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0042_alter_applicationmodel_cell_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="Cell_Phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
