# Generated by Django 6.0.6 on 2026-07-20 15:39

import applications.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0043_alter_applicationmodel_cell_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="Bank_Statement",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applications.functions.Bank_Statement_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Business_Registration",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applications.functions.Business_Registration_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Financial_Statement",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applications.functions.Financial_Statement_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Job_Letter",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applications.functions.Job_Letter_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Selfie",
            field=models.FileField(upload_to=applications.functions.Selfie_upload_path),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Statement",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applications.functions.Statement_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Utility_Bill",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applications.functions.Utility_Bill_upload_path,
            ),
        ),
    ]
