# Generated by Django 6.0.6 on 2026-07-20 16:02

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0044_alter_applicationmodel_bank_statement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="Cell_Phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="e.g., 246-555-1234 or +12465551234",
                max_length=128,
                region="BB",
            ),
        ),
    ]
