# Generated by Django 6.0.6 on 2026-07-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0045_alter_applicationmodel_cell_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="email",
            field=models.EmailField(
                help_text="Enter a valid email address", max_length=254
            ),
        ),
    ]
