# Generated by Django 5.2.16 on 2026-07-20 19:12

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0046_alter_applicationmodel_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="Home_Phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="e.g., 246-555-1234 or +12465551234",
                max_length=128,
                null=True,
                region="BB",
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Prefix",
            field=models.CharField(
                choices=[("Mr", "Mr"), ("Mrs", "Mrs"), ("Miss", "Miss"), ("Ms", "Ms")],
                default="Mr",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="Work_Phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="e.g., 246-555-1234 or +12465551234",
                max_length=128,
                null=True,
                region="BB",
            ),
        ),
    ]
