# Generated by Django 5.2.16 on 2026-07-21 11:41

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0048_applicationmodel_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="Employer_Num",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+12460000000",
                help_text="e.g., 246-555-1234 or +12465551234",
                max_length=128,
                region="BB",
            ),
        ),
    ]
