# Generated by Django 5.2.16 on 2026-07-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0049_applicationmodel_employer_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationmodel",
            name="Cell_Phone",
            field=models.CharField(
                default="+12465645676",
                help_text="e.g., 246-555-1234 or +12465551234",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Employer_Num",
            field=models.CharField(
                default="+12465645676",
                help_text="e.g., 246-555-1234 or +12465551234",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Home_Phone",
            field=models.CharField(
                blank=True,
                default="+12465645676",
                help_text="e.g., 246-555-1234 or +12465551234",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference1_Contact_Number",
            field=models.CharField(
                default="+12465645676",
                help_text="e.g., 246-555-1234 or +12465551234",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference2_Contact_Number",
            field=models.CharField(
                default="+12465645676",
                help_text="e.g., 246-555-1234 or +12465551234",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Work_Phone",
            field=models.CharField(
                blank=True,
                default="+12465645676",
                help_text="e.g., 246-555-1234 or +12465551234",
                max_length=20,
                null=True,
            ),
        ),
    ]
