# Generated by Django 5.2.16 on 2026-07-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0050_alter_applicationmodel_cell_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="reference_number",
            field=models.CharField(
                blank=True,
                help_text="Unique reference number for this application (e.g., ESS-000001)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
