# Generated by Django 5.2.16 on 2026-07-27 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0051_applicationmodel_reference_number"),
        ("payments", "0002_alter_paymentrecord_loan"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="deposit_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Deposit amount paid",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="deposit_paid_date",
            field=models.DateTimeField(
                blank=True, help_text="When deposit was paid", null=True
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="deposit_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_deposit",
                to="payments.paymentrecord",
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="deposit_payment_method",
            field=models.CharField(
                blank=True,
                help_text="How deposit was paid (Cash, POS, Bank Transfer, etc.)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="deposit_receipt_number",
            field=models.CharField(
                blank=True,
                help_text="Receipt number for deposit payment",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applicationmodel",
            name="deposit_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid - Awaiting Loan Creation"),
                    ("TRANSFERRED", "Transferred to Loan"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                help_text="Status of the deposit payment",
                max_length=20,
            ),
        ),
    ]
