# Generated by Django 5.2.16 on 2026-08-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0052_applicationmodel_deposit_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationmodel",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Length_at_Address",
            field=models.IntegerField(
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, "10+"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Num_Dependents",
            field=models.IntegerField(
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, "10+"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference1_Len_Time_Known",
            field=models.IntegerField(
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, "10+"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="applicationmodel",
            name="Reference2_Len_Time_Known",
            field=models.IntegerField(
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, "10+"),
                ]
            ),
        ),
    ]
