# Generated by Django 5.2.16 on 2026-08-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0053_applicationmodel_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("APPROVAL", "Approval Email"),
                            ("STAFF_NOTIFICATION", "Staff Notification"),
                            ("APPLICATION_CONFIRMATION", "Application Confirmation"),
                            ("REMINDER", "Payment Reminder"),
                            ("REGISTRATION", "Registration Link"),
                            ("REJECTION", "Rejection Email"),
                        ],
                        max_length=50,
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="sent", max_length=20)),
                ("message_id", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["sent_at"], name="application_sent_at_a798bb_idx"
                    ),
                    models.Index(
                        fields=["email_type"], name="application_email_t_c2c9c5_idx"
                    ),
                ],
            },
        ),
    ]
