# Generated by Django 6.0.6 on 2026-07-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_sitesettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="updated_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
