# Generated by Django 6.0.6 on 2026-07-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_alter_sitesettings_options_sitesettings_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="maintenance_message",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="maintenance_title",
        ),
    ]
