# Generated by Django 5.2.16 on 2026-08-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="customer_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
