# Generated by Django 6.0.6 on 2026-06-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("EMAIL_SENT", "Email Sent"),
                    ("EMAIL_FAILED", "Email Failed"),
                    ("EMAIL", "Email"),
                    ("ERROR", "Error"),
                ],
                max_length=20,
            ),
        ),
    ]
