# Generated by Django 5.2.16 on 2026-07-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditlog_action"),
        ("loans", "0005_loanproduct_notes_alter_loannote_loan"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="loan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="loans.loanproduct",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("EMAIL_SENT", "Email Sent"),
                    ("EMAIL_FAILED", "Email Failed"),
                    ("EMAIL", "Email"),
                    ("ERROR", "Error"),
                    ("PAYMENT_MADE", "Payment Made"),
                    ("PAYMENT_REVERSED", "Payment Reversed"),
                    ("LOAN_CREATED", "Loan Created"),
                    ("LOAN_ACTIVATED", "Loan Activated"),
                    ("LOAN_CLOSED", "Loan Closed"),
                    ("LOAN_REPAIRED", "Loan Repaired"),
                    ("HP_ACCOUNT_CREATED", "HP Account Created"),
                    ("QB_SYNC_SUCCESS", "QuickBooks Sync Success"),
                    ("QB_SYNC_FAILED", "QuickBooks Sync Failed"),
                    ("DEPOSIT_RECEIVED", "Deposit Received"),
                ],
                max_length=20,
            ),
        ),
    ]
