# Generated by Django 5.2.16 on 2026-08-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_auditlog_loan_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("EMAIL_SENT", "Email Sent"),
                    ("EMAIL_FAILED", "Email Failed"),
                    ("EMAIL", "Email"),
                    ("ERROR", "Error"),
                    ("PAYMENT_MADE", "Payment Made"),
                    ("PAYMENT_REVERSED", "Payment Reversed"),
                    ("PAYMENT_REVERSED_BY_ADMIN", "Payment Reversed by admin"),
                    ("PAYMENT_REINSTATED_BY_ADMIN", "Payment Reinstated by admin"),
                    ("LOAN_CREATED", "Loan Created"),
                    ("LOAN_ACTIVATED", "Loan Activated"),
                    ("LOAN_CLOSED", "Loan Closed"),
                    ("LOAN_REPAIRED", "Loan Repaired"),
                    ("HP_ACCOUNT_CREATED", "HP Account Created"),
                    ("QB_SYNC_SUCCESS", "QuickBooks Sync Success"),
                    ("QB_SYNC_FAILED", "QuickBooks Sync Failed"),
                    ("DEPOSIT_RECEIVED", "Deposit Received"),
                    (
                        "CASH_DEPOSIT_RECORDED_BY_ADMIN",
                        "Cash Deposit Recorded by Admin",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
