# Generated by Django 5.2.16 on 2026-07-22 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0051_applicationmodel_reference_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installment_number", models.IntegerField()),
                ("due_date", models.DateField()),
                ("principal_due", models.DecimalField(decimal_places=2, max_digits=12)),
                ("interest_due", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_due", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "principal_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "interest_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIAL", "Partial"),
                            ("PAID", "Paid"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["installment_number"],
            },
        ),
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_id", models.CharField(max_length=20, unique=True)),
                (
                    "deposit_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("deposit_paid_date", models.DateTimeField(blank=True, null=True)),
                (
                    "deposit_payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "deposit_receipt_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tenure_months", models.IntegerField()),
                (
                    "monthly_installment",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_interest",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_payable", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "outstanding_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("DELINQUENT", "Delinquent"),
                            ("DEFAULTED", "Defaulted"),
                            ("PAID_OFF", "Paid Off"),
                            ("WRITTEN_OFF", "Written Off"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("creation_method", models.CharField(default="AUTO", max_length=20)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("first_payment_date", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quickbooks_customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "quickbooks_invoice_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quickbooks_synced_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applications.applicationmodel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
