# Generated by Django 5.2.16 on 2026-07-22 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanproduct",
            name="deposit_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.paymentrecord",
            ),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_schedule",
                to="loans.loanproduct",
            ),
        ),
    ]
