# Generated by Django 5.2.16 on 2026-07-23 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="loanproduct",
            old_name="notes",
            new_name="internal_notes",
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="grace_period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="late_fee_assessed",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="late_fee_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="payment_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installment_paid",
                to="payments.paymentrecord",
            ),
        ),
        migrations.AlterField(
            model_name="paymentschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PARTIAL", "Partial"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CollectionActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("PHONE_CALL", "Phone Call"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("LETTER", "Letter"),
                            ("VISIT", "Visit"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "contact_status",
                    models.CharField(
                        choices=[
                            ("CONTACTED", "Contacted"),
                            ("NO_ANSWER", "No Answer"),
                            ("WRONG_NUMBER", "Wrong Number"),
                            ("PROMISE_TO_PAY", "Promise to Pay"),
                            ("DISPUTE", "Dispute"),
                            ("ESCALATED", "Escalated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("promise_date", models.DateField(blank=True, null=True)),
                (
                    "promise_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("promise_fulfilled", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_activities",
                        to="loans.loanproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Activity",
                "verbose_name_plural": "Collection Activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("LATE", "Late Payment Fee"),
                            ("PROCESSING", "Processing Fee"),
                            ("MAINTENANCE", "Maintenance Fee"),
                            ("ADMIN", "Administrative Fee"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True)),
                ("assessed_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                ("is_waived", models.BooleanField(default=False)),
                ("waived_date", models.DateTimeField(blank=True, null=True)),
                ("waiver_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="loans.loanproduct",
                    ),
                ),
                (
                    "payment_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_paid",
                        to="payments.paymentrecord",
                    ),
                ),
                (
                    "waived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waived_fees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Fee",
                "verbose_name_plural": "Loan Fees",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="LoanNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Note"),
                            ("COLLECTION", "Collection Note"),
                            ("CUSTOMER_REQUEST", "Customer Request"),
                            ("INTERNAL", "Internal Note"),
                            ("DISPUTE", "Dispute"),
                            ("RESOLUTION", "Resolution"),
                        ],
                        default="GENERAL",
                        max_length=50,
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=True, help_text="If True, customer cannot see this note"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="loans.loanproduct",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Note",
                "verbose_name_plural": "Loan Notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("DELINQUENT", "Delinquent"),
                            ("DEFAULTED", "Defaulted"),
                            ("PAID_OFF", "Paid Off"),
                            ("WRITTEN_OFF", "Written Off"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("DELINQUENT", "Delinquent"),
                            ("DEFAULTED", "Defaulted"),
                            ("PAID_OFF", "Paid Off"),
                            ("WRITTEN_OFF", "Written Off"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="loans.loanproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Status History",
                "verbose_name_plural": "Loan Status Histories",
                "ordering": ["-changed_at"],
            },
        ),
    ]
