# Generated by Django 5.2.16 on 2026-07-27 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_rename_notes_loanproduct_internal_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentschedule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
