# Generated by Django 5.2.16 on 2026-07-27 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_paymentschedule_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanproduct",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loannote",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_notes",
                to="loans.loanproduct",
            ),
        ),
    ]
