# Generated by Django 5.2.16 on 2026-08-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0006_alter_loanproduct_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanproduct",
            name="deposit_complete",
            field=models.BooleanField(
                default=False, help_text="True when deposit_paid >= deposit_target"
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="deposit_target",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total deposit required to activate the loan (e.g., 10% of principal)",
                max_digits=12,
            ),
        ),
    ]
