# Generated by Django 5.2.16 on 2026-08-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0007_loanproduct_deposit_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanproduct",
            name="total_principal_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
