# Generated by Django 5.2.16 on 2026-08-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0008_loanproduct_total_principal_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanproduct",
            name="total_interest_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
