# Generated by Django 5.2.16 on 2026-08-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0009_loanproduct_total_interest_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanproduct",
            name="quickbooks_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
